#############################################################################
# Makefile for building: Sudoku.app/Contents/MacOS/Sudoku
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  Sudoku.pro
# Template: app
# Command: /usr/local/Cellar/qt@5/5.15.2/bin/qmake -o Makefile Sudoku.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib -I/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers -I/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt@5/5.15.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt@5/5.15.2/mkspecs/macx-clang -F/usr/local/Cellar/qt@5/5.15.2/lib
QMAKE         = /usr/local/Cellar/qt@5/5.15.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Cellar/qt@5/5.15.2/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Cellar/qt@5/5.15.2/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Sudoku1.0.0
DISTDIR = /Users/willump/fun/Sudoku/.tmp/Sudoku1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt@5/5.15.2/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Sudoku.cpp 
OBJECTS       = main.o \
		Sudoku.o
DIST          = /usr/local/Cellar/qt@5/5.15.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/lex.prf \
		Sudoku.pro  main.cpp \
		Sudoku.cpp
QMAKE_TARGET  = Sudoku
DESTDIR       = 
TARGET        = Sudoku.app/Contents/MacOS/Sudoku

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/willump/fun/Sudoku/Sudoku.pro


include /usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Sudoku.app/Contents/MacOS/Sudoku:  $(OBJECTS)  
	@test -d Sudoku.app/Contents/MacOS/ || mkdir -p Sudoku.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Sudoku.pro /usr/local/Cellar/qt@5/5.15.2/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt@5/5.15.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/lex.prf \
		Sudoku.pro \
		/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Cellar/qt@5/5.15.2/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Sudoku.pro
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/qdevice.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/macx.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt@5/5.15.2/mkspecs/features/lex.prf:
Sudoku.pro:
/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Cellar/qt@5/5.15.2/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Sudoku.pro

qmake_all: FORCE

Sudoku.app/Contents/PkgInfo: 
	@test -d Sudoku.app/Contents || mkdir -p Sudoku.app/Contents
	@$(DEL_FILE) Sudoku.app/Contents/PkgInfo
	@echo "APPL????" > Sudoku.app/Contents/PkgInfo
Sudoku.app/Contents/Resources/empty.lproj: 
	@test -d Sudoku.app/Contents/Resources || mkdir -p Sudoku.app/Contents/Resources
	@touch Sudoku.app/Contents/Resources/empty.lproj
	
Sudoku.app/Contents/Info.plist: 
	@test -d Sudoku.app/Contents || mkdir -p Sudoku.app/Contents
	@$(DEL_FILE) Sudoku.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Sudoku,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Sudoku,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Sudoku,g" -e "s,@LIBRARY@,Sudoku,g" -e "s,\$${EXECUTABLE_NAME},Sudoku,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt@5/5.15.2/mkspecs/macx-clang/Info.plist.app >Sudoku.app/Contents/Info.plist

all: Makefile \
		Sudoku.app/Contents/PkgInfo \
		Sudoku.app/Contents/Resources/empty.lproj \
		Sudoku.app/Contents/Info.plist Sudoku.app/Contents/MacOS/Sudoku

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt@5/5.15.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Sudoku.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Sudoku.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt@5/5.15.2/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/Cellar/qt@5/5.15.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp /usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Sudoku.o: Sudoku.cpp /usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/Python.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/patchlevel.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyconfig.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pymacconfig.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyport.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/exports.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pymacro.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pymath.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pytime.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/object.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/object.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pymem.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/pymem.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/objimpl.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/objimpl.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/typeslots.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyhash.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pydebug.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/bytearrayobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/bytearrayobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/bytesobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/bytesobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/unicodeobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/unicodeobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/longobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/longintrepr.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/boolobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/floatobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/complexobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/rangeobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/memoryobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/tupleobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/tupleobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/listobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/listobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/dictobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/dictobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/odictobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/enumobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/setobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/methodobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/methodobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/moduleobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/funcobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/classobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/fileobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/fileobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pycapsule.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/code.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/code.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyframe.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/traceback.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/traceback.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/sliceobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cellobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/iterobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/genobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pystate.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/pystate.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/initconfig.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/descrobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/genericaliasobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/warnings.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/weakrefobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/structseq.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/namespaceobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/picklebufobject.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/codecs.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyerrors.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/pyerrors.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pythread.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/context.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyarena.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/modsupport.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/compile.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pythonrun.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pylifecycle.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/pylifecycle.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/ceval.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/ceval.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/sysmodule.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/sysmodule.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/osmodule.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/intrcheck.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/import.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/import.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/abstract.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/abstract.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/bltinmodule.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/eval.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyctype.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pystrtod.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pystrcmp.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/fileutils.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/cpython/fileutils.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/pyfpe.h \
		/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/Headers/tracemalloc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sudoku.o Sudoku.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

